/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
import animations from "@midudev/tailwind-animations";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      gradienteTijeras: "hsl(39, 89%, 49%)",
      gradienteTijeras2: "hsl(40, 84%, 53%)",
      gradientePapel: "hsl(230, 89%, 62%)",
      gradientePapel2: "hsl(230, 89%, 65%)",
      gradienteRoca: "hsl(349, 71%, 52%)",
      gradienteRoca2: "hsl(349, 70%, 56%)",
      gradienteLagarto: "hsl(261, 73%, 60%)",
      gradienteLagarto2: "hsl(261, 72%, 63%)",
      cyan: "hsl(189, 59%, 53%)",
      cyan2: "hsl(189, 58%, 57%)",
      textoOscuro: "hsl(229, 25%, 31%)",
      textoPuntos: "hsl(229, 64%, 46%)",
      lineaEncabezado: "hsl(217, 16%, 45%)",
      gradienteFondo: "hsl(214, 47%, 23%)",
      gradienteFondo2: "hsl(237, 49%, 15%)",
      transparent: "transparent",
      current: "currentColor",
      black: "#000",
      white: "#fff",
      bluegray: colors.blueGray,
      coolgray: colors.coolGray,
      gray: colors.gray,
      truegray: colors.trueGray,
      warmgray: colors.warmGray,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    },
    extend: {},
  },
  plugins: [require("flowbite/plugin"), animations],
};
